app/models/raw_storer.rb, app/models/storer.rb, public/examples/sockets.html, spec/models/storer_spec.rb
* Removes unused information from the websockets payload and maintains there just the device view
* Updates the websocket example accordingly
* Pushes the websockets message only when a reading has been properly ingested
* When multiple readings are sent (like during CSV upload) we push a single websocket to reduce the overhead. This means the data-received websockets channel is not intended to provide all the data received but just a notification data has been received
* Model has also been refactored to make data flows more explicit (the same work might be done in raw storer)
=> Simplifies websockets data-received payload

app/lib/mqtt_messages_handler.rb, spec/lib/mqtt_messages_handler_spec.rb
TODO:
Sentry error screenshot:
=> Handle device not found

config/environments/production.rb, scripts/nginx-conf/api.smartcitizen.me.conf
Was causing http urls instead of https. see:
https://github.com/fablabbcn/smartcitizen-api/issues/166
Solution is to force use SSL, and forward it from Nginx to the container
See more: https://github.com/rails/rails/issues/22965
If this works without problems, we can also update the **auth** container to use `force_ssl = true`
=> Force SSL + Forward SSL from Nginx to the container

env.example, lib/tasks/mqtt_subscriber.rake
Sets the platform MQTT subscriber on persistent connection mode, enabling the app to recover all the non ingested messages from the broker if it accidentally disconnects
=> Feat mqtt persistance

app/lib/mqtt_messages_handler.rb, docs/mqtt.md, spec/lib/mqtt_messages_handler_spec.rb
Add handling for raw readings published by the kit in `device/sck/device_token:/readings/raw` topic.
With this change the size of the payload is reduced to around 35% of original size.
[This](https://github.com/fablabbcn/smartcitizen-kit-21/commit/f195dbc010c8cddc419cb4357875c9de942aab48) is the firmware commit that enables raw readings publishing on the kit side.
=> Handle raw readings published on `device/sck/device_token:/readings/raw`

app/jobs/delete_archived_devices_job.rb, app/models/device.rb, db/migrate/20230512075843_add_archived_at_to_devices.rb, db/schema.rb, spec/jobs/delete_archived_devices_job_spec.rb, spec/models/device_spec.rb
This fixes #214 - deleting devices failed since we moved the postprocessing data to a seperate table, as the foreign key constraint prevented the postprocessing table entry being orphaned.
The solution is to make this relationship `depenedent: destroy` - when a device is removed, we remove its postprocessing info too.
I've also added a test to guard against regressions here and make the behaviour we expect explicit.
=> Fix PG foreign key error on deleting devices

app/models/device.rb, app/services/device_archive.rb, spec/lib/mqtt_messages_handler_spec.rb, spec/models/device_spec.rb
Metrics provided by an HTTP post after postprocessing were showing up out-of-order
in the CSV, apended after the sensor data received directly. This was due to the fact that
the CSV table is built column-wise rather than row-wise, and ruby hashes preserve the order of
insertion, not of their keys, as detailed in #215 .
To fix this, we've added an explicit sort by timestamp at the end, this returns an array rather
than a hash, so have renamed the method and refactored to suit.
Still TODO: better test coverage and some refactoring of this class, as this logic could be made
much clearer.
=> Bugfix: CSV download sort order (#215)

app/views/v0/users/_user.jbuilder, config/environments/development.rb, config/initializers/force_ssl.rb
This i've tested succesfully in staging - the fact that it relies on SSL makes it difficult to write specs for
```json
{
"id": 3,
"uuid": "6c9a7299-e315-4a32-a36c-b6df730dafa5",
"role": "admin",
"username": "tim",
"avatar": "https://smartcitizen.s3.amazonaws.com/avatars/default.svg",
"profile_picture": "https://staging-api.smartcitizen.me/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae4708c28450a738096a6dfeeaa9e7aab12086ac/tim.jpg",
"url": null,
"location": {
"city": null,
"country": null,
"country_code": null
},
"joined_at": "2023-05-25T06:54:00Z",
"updated_at": "2023-05-25T06:55:51Z",
"email": "[FILTERED]",
"legacy_api_key": "[FILTERED]",
"devices": []
}
```
In case of any issues, it might be worth  running `rails …
=> WIP - use https for user profile urls

db/migrate/20230705095430_populate_device_archived_at_column.rb, db/schema.rb
This corrects an oversight in my previous PR which created the field but didn't set it for previously-archived devices.
=> Populate archived_at field on devices for archived devices

app/models/postprocessing.rb, spec/requests/v0/devices_spec.rb
Fixes #254 - this is an API change in the new version of Ransack - searchable parameters have to be explicitly whitelisted. We probably need to investigate to see if there are any others that are used habitually, in the meantime this will fix the immediate issue with postprocessings.
=> Ensure that devices are searchable by the presence of a postprocessing

scripts/Dockerfile-kairos
The previous java8 / alpine linux container was removed, so instead we're using the openjdk 8 alpine image. This builds and runs locally, but will need some thorough testing in staging.
=> Update base image for Kairos docker container.

config/initializers/sentry.rb
Sentry has a [feature called breadcrumbs](https://docs.sentry.io/platforms/ruby/configuration/options/) which might help us track down some of those weirder bugs (the Puma one, and the JSON one)? This enables it in the api.
=> Enable sentry breadcrumbs

app/lib/mqtt_messages_handler.rb, config/initializers/sentry.rb
Enabled Sentry's [Sidekiq integration](https://docs.sentry.io/platforms/ruby/guides/sidekiq/) properly, and added some manual [Breadcrumbs](https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/breadcrumbs/) to better track what's going on in the MQTT message handler.
If we could get this to production when we meet next week so i can better understand those last few remaining errors from the upgrade, that'd be ace!
=> Better sentry logging in MQTT message handler

app/controllers/v0/application_controller.rb, app/controllers/v0/devices_controller.rb, app/controllers/v0/sensors_controller.rb, app/controllers/v0/users_controller.rb, app/models/device.rb, app/models/postprocessing.rb, app/models/sensor.rb, app/models/tag.rb, app/models/user.rb, config/initializers/ransack.rb, spec/controllers/v0/devices_controller_spec.rb, spec/models/device_spec.rb, spec/requests/v0/devices_spec.rb, spec/requests/v0/sensors_spec.rb, spec/requests/v0/users_spec.rb
Fixes #256 : Our documentation advertises that users, devices, and sensors are searchable with ransack - this commit adds some tests that assert (in a very basic manner) that this will succeed, and fixes a few cases where we weren't actually supporting the behaviour we advertise.
=> Add tests for advertised ransack parameters and fix regressions

lib/tasks/mqtt_subscriber.rake, lib/tasks/telnet.rake
This ensures that the Sentry scope is reset on each new telnet or mqtt message ,for easier tracing of errors. @oscgonfer I've tested in staging and it looks good, if we could push to production when you have a sec it'd be super useful!
=> set sentry scopes properly in rake tasks

app/controllers/application_controller.rb, app/controllers/v0/application_controller.rb, app/helpers/user_helper.rb, app/views/v0/devices/_device.jbuilder, app/views/v0/devices/index.jbuilder, app/views/v0/users/_user.jbuilder, lib/tasks/import.rake
Needed for #166  - Currently, in various places where fablabbcn/smartcitizen-web renders a user, no profile picture is provided, leaving the default avatar showing.
I've also added a task `rake import:old_avatar_images` which will copy the old avatar across to the profile_picture for all users with an avatar who don't yet have a profile_picture. This will probably not do much in staging as it uses a different s3 bucket, but works well locally setting the credentials manually. When we run in production we should keep an eye on sidekiq to make sure the ActiveStorage AnalysisJobs complete successfully.
=> Move all avatars to profile_picture and ensure that profile_picture is included in responses

config/initializers/countries.rb
A little bit of friday morning unilateral geopolitics, in order to fix https://iaac.sentry.io/issues/4488943927 (at least temporarily until the ISO grants it an official country code)
=> Add Country data for Kosovo

app/lib/mqtt_messages_handler.rb
As otherwise the `data` hash doesn't show up in the sentry UI, slightly defeating the point.
=> Scrub unicode before creating sentry breadcrumbs

app/controllers/v0/static_controller.rb
Another small piece of the jigsaw for #166 - currently user icons don't show in search results as the profile_picture is not provided in the response.
=> ensure profile_picture is sent for users in search results

app/controllers/v0/application_controller.rb, app/controllers/v0/static_controller.rb
Sorry, tiny change from my last PR on this! We need to return the profile image url, and not the object itself.
=> use profile image url and not object in search results

app/views/v0/devices/_device.jbuilder, app/views/v0/users/_user.jbuilder, spec/requests/v0/users_spec.rb
If the current authenticated user is the user being requested, they are visible
If the current authenticated user is an admin, they are visible
If there is no current user, or the current user is a different citizen or researcher, they are not.
=> Ensure /users/:id endpoint only lists private devices when the requesting user is authorized to see them

app/views/v0/devices/_device.jbuilder, spec/requests/v0/devices_spec.rb
as requeste in #289 - I've taken the same pattern we use for the `mac_address` - we display the text '[FILTERED]' unless the logged in user is the owner or an admin.
=> expose device token in /devices/:id endpoint to device owner and admins

compose/web.yml, scripts/nginx-conf/api.smartcitizen.me.conf
This enables strict end-to-end encryption on cloudflare.
=> Allow nginx to listen with SSL on port 443

app/jobs/retry_mqtt_message_job.rb, app/lib/mqtt_messages_handler.rb, config/initializers/sentry.rb, config/sidekiq.yml, spec/jobs/retry_mqtt_message_job_spec.rb, spec/lib/mqtt_messages_handler_spec.rb
Since we deployed the devices refactor, a slightly subtle bug (#314) has emerged: if a device sends the hardware_info packet before the user has completed registration, the device is not found, the info is not saved, and therefore the device information in the UI is incomplete. This (hopefully, I like to test on staging with a real device) fixes this by relying on Sidekiq's built in error handling functionality to retry the hardware_info message (with backoff) in the event that no device corresponds to the given key. Sidekiq defaults to 25 retries with backoff (corresponding to about 3 weeks of elapsed time between the first and the last try), which should be sufficient: https://docs.gitlab.com/ee/development/sidekiq/.
=> Deferred retry of hardware_info handling when device not found

app/controllers/v0/forwarding_controller.rb, app/controllers/v0/readings_controller.rb, app/jobs/retry_mqtt_message_job.rb, app/jobs/send_to_datastore_job.rb, app/lib/mqtt_client_factory.rb, app/lib/mqtt_forwarder.rb, app/lib/mqtt_messages_handler.rb, app/models/concerns/message_forwarding.rb, app/models/device.rb, app/models/raw_storer.rb, app/models/storer.rb, app/models/user.rb, config/routes.rb, db/migrate/20240423162838_add_forwarding_token_to_users.rb, db/migrate/20240512132257_add_forwarding_username_to_users.rb, db/schema.rb, lib/tasks/mqtt_subscriber.rake, spec/jobs/retry_mqtt_message_job_spec.rb, spec/lib/mqtt_messages_handler_spec.rb, spec/models/device_spec.rb, spec/models/raw_storer_spec.rb, spec/models/storer_spec.rb, spec/models/user_spec.rb, spec/requests/v0/forwarding_spec.rb
WIP on #226.
Includes the creation of forwarding tokens for users and logic to decide whether or not to forward, plus the machinery for doing the forwarding. It's involved a bit more refactoring work than i thought as we need to manage the MQTT client object lifecycle a bit more carefully and pass it around to where its needed. For further discussion and testing on staging on Friday!
=> Forwarding of device data

app/controllers/v0/devices_controller.rb, app/models/device.rb, app/views/v0/devices/_device.jbuilder, db/migrate/20240624161155_add_data_policy_fields_to_device.rb, lib/tasks/devices.rake, spec/models/device_spec.rb, spec/requests/v0/devices_spec.rb
- enable_forwarding allows forwarding to be enabled or disabled per device
- precise_location allows users to choose whether precise (5dp) or approxmite (3dp + 2dp of noise) locations are stored.
On deploying we will need to run migrations, then run rake devices:truncate_and_fuzz_locations in order to truncate the existing locations to 5dp.
=> Add new data policy fields

app/controllers/v0/readings_controller.rb, app/jobs/mqtt_forwarding_job.rb, app/jobs/retry_mqtt_message_job.rb, app/jobs/send_to_datastore_job.rb, app/lib/mqtt_messages_handler.rb, app/models/concerns/message_forwarding.rb, app/models/raw_storer.rb, app/models/storer.rb, config/sidekiq.yml, lib/tasks/mqtt_subscriber.rake, spec/jobs/mqtt_forwarding_job_spec.rb, spec/jobs/retry_mqtt_message_job_spec.rb, spec/lib/mqtt_messages_handler_spec.rb, spec/models/raw_storer_spec.rb, spec/models/storer_spec.rb
MQTT message forwarding logic happens in a sidekiq job so as to not block the mqtt listener thread
=> Forwarding in job

.dockerignore
This speeds up build time on staging, where we run cassandra locally, and stops the built images getting unnecessarily enormous
=> ignore cassandra data in docker build

app/jobs/delete_archived_devices_job.rb, spec/jobs/delete_archived_devices_job_spec.rb
Some devices in production are archived, but don't have an archived_at date. this ensures they don't crash the device archive job.
=> fix device archived_at null bug

app/models/user.rb, app/views/v0/users/_user.jbuilder, lib/tasks/users.rake, spec/models/user_spec.rb, spec/requests/v0/users_spec.rb
Forwarding tokens are now available to logged in users for their own account, and to admins for everyone, on the /users endpoint.
Tokens are generated automatically for researchers and admins  on creation or privilege escalation
A new rake task `users:generate_forwarding_tokens` in order to backfill tokens for existing users without them
=> generate and expose forwarding tokens and usernames

app/controllers/v0/experiments_controller.rb, app/models/device.rb, app/models/experiment.rb, app/models/validators/datetime_validator.rb, app/policies/experiment_policy.rb, app/views/v0/devices/_device.jbuilder, app/views/v0/experiments/_experiment.jbuilder, app/views/v0/experiments/index.jbuilder, app/views/v0/experiments/show.jbuilder, config/routes.rb, db/migrate/20240718054447_create_experiments.rb, db/migrate/20240812081108_remove_active_flag_from_experiments.rb, db/schema.rb, spec/factories/experiment.rb, spec/models/experiment_spec.rb, spec/requests/v0/devices_spec.rb, spec/requests/v0/experiments_spec.rb
Experiments are groups of devices which are being used as part of a single experiment.
An experiment has an optional start and end time, and is owned by a user - the user does not need to own the participating devices.
you get GET/PUT/PATCH/POST/DELETE to the /v0/experiments endpoint with json like:
```json
{
"name": "test experiment",
"description": "a test experiment",
"is_test": false,
"active": true,
"starts_at": "2024-01-01T00:00:00Z",
"ends_at": "2024-06-30T23:59:59Z",
"device_ids": [ 123, 456, 789 ]
}
```
=> Add models and endpoints for Experiments

config/routes.rb
Ensure that users who have a dot in their usernames are accessible on the /users endpoint
=> ensure users with usernames containing a dot can be displayed

app/controllers/v0/users_controller.rb, spec/requests/v0/users_spec.rb
Allow admins to promote or demote user roles by passing a role_mask when updating:
eg `curl 'https://staging-api.smartcitizen.me/v0/users/USERNAME' -X PATCH -H 'Content-Type: application/json;charset=UTF-8' -H 'Authorization: Bearer API_TOKEN' --data-binary '{"role_mask": 2}' --compressed`
=> admin users can update user role mask

compose/app.yml, compose/web.yml
Ensures there's no downtime when the oom_killer runs
=> healthchecks to restart web container when app restarted

app/models/device.rb, app/views/v0/devices/_device.jbuilder, app/views/v0/devices/_world_map_device.jbuilder, app/views/v0/devices/_world_map_list.jbuilder, config/application.rb
Only send the fields we need to render the world map. We also add Rack::Deflate middleware to gzip all json responses.
Partially addresses: https://github.com/fablabbcn/smartcitizen-web/issues/451#issuecomment-2402331215
Overall, this cuts the weight of the world map from ~4.5MB to ~250k, and the response time down to approx 1.5 sec.
The speed up from caching the /world_map endpoint is now negligible, so we might think about removing that once we've verified that this all works correctly.
=> slim world map representation and add gzip middleware

Gemfile, Gemfile.lock, app/models/component.rb, app/models/concerns/data_parser/storer.rb, app/models/device.rb, app/models/raw_storer.rb, app/models/storer.rb, compose.override.local.yml, compose/app.yml, compose/db.yml, compose/mqtt-task-common.yml, compose/mqtt-task.yml, compose/telnet-task.yml, db/migrate/20241009174732_unique_index_on_components.rb, db/schema.rb, env.example, lib/tasks/mqtt_subscriber.rake, mqtt_subscriber.sh, spec/models/component_spec.rb, spec/models/device_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
Addresses #355, allowing us to scale the mqtt task through parallel processing. We have two named "main" subscribers which ensure that messages are not dropped in the event of downtime (they have consistent client ids and persistent sessions), and a secondary subscriber role (with transient ids and clean sessions) which can be scaled with load. Needs *thorough* testing on staging before deployment!
:warning: **on deployment, we need to:** :warning:
- **bring down the app entirely, including the old mqtt-task**
-  **delete the old "mqtt subscriber" client in emqx, so that no messages are retained for it, as the client id changes in this release**
-  **run migrations BEFORE bringing up the mqtt-task again, as otherwise duplicate components will be created**
- **bring up the entire stack …
=> MQTT subscription

Gemfile, Gemfile.lock, app/lib/mqtt_messages_handler.rb, app/lib/raw_mqtt_message_parser.rb, app/mailers/user_mailer.rb, app/models/component.rb, app/models/concerns/data_parser/storer.rb, app/models/device.rb, app/models/ingest_error.rb, app/models/raw_storer.rb, app/models/storer.rb, app/views/user_mailer/device_ingest_errors.html.erb, compose.override.local.yml, compose/app.yml, compose/db.yml, compose/mqtt-task-common.yml, compose/mqtt-task.yml, compose/telnet-task.yml, db/migrate/20241009174732_unique_index_on_components.rb, db/migrate/20241014052837_create_device_ingest_errors.rb, db/schema.rb, env.example, lib/tasks/mqtt_subscriber.rake, mqtt_subscriber.sh, spec/lib/raw_mqtt_message_parser_spec.rb, spec/models/component_spec.rb, spec/models/device_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
Log all ingest errors against the device, and notify users periodically if their device causes ingest errors, prompting them to upgrade. Addresses #288.
Merge #362 first, as this branch is based off that one
=> Device error logging

compose/web.yml
This is another attempt to help with `web` not restarting when `app` falls over. It adds a `healthcheck` on **runtime** to the web container. It seems that the `depends_on` done in https://github.com/fablabbcn/smartcitizen-api/pull/360 only works for docker compose operations, not in runtime. 
This is indicated in the documentation: https://docs.docker.com/reference/compose-file/services/#depends_on
> restart: When set to true Compose restarts this service after it updates the dependency service. This applies to an explicit restart controlled by a Compose operation, and excludes automated restart by the container runtime after the container dies. Introduced in Docker Compose version 2.17.0.
=> Add healthcheck on web to restart based on curl

config/initializers/sentry.rb
We don't want to use up our Sentry quota with errors which are simple 404s
=> don't log 404s in sentry

app/models/kairos.rb, spec/requests/v0/password_resets_spec.rb
Fixes #374, gives each device a `first_reading_at` property, populated on ingest, and allows passing of a `limit` parameter to the readings endpoint (applied **before** rollups)
:rotating_light: REQUIRES migrations and the `devices:set_first_reading_at` task to be run on deploy :rotating_light:
=> Postprocessing data read enhancements

app/controllers/ui/devices_controller.rb, app/controllers/v0/devices_controller.rb, app/lib/presenters/device_presenter.rb, app/models/device.rb, app/models/forwarding_destination.rb, app/views/ui/devices/_fields.html.erb, config/locales/views/devices/en.yml, db/migrate/20250715180503_add_forwarding_destinations.rb, db/schema.rb
This PR adds the concept of a "forwarding destintation" for devices, which allows us to reroute and transform MQTT forwarded messages for specific downstream research projects.
We can create a new forwarding destination in the console with eg `ForwardingDestination.create(name: "important_eu_research_project")`, this will then be made available, for researcher users, in the "forwarding destination" dropdown on the edit device page.
If a user selects a forwarding destination apart from the default on the device edit page, then this will be included as an extra parameter in the `data_policy` section on both the API and in forwarded MQTT packets.
This allows us to set up custom forwarding rules in EMQX for these packets.
We can also search for all devices which are forwarding to a given …
=> Forwarding Destinations
